name: run

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: data
    - name: Clone Neo Node
      uses: actions/checkout@v2
      with:
        repository: neo-project/neo-node
        ref: v3.0.2
        path: .node
    - name: Clone Neo Modules
      uses: actions/checkout@v2
      with:
        repository: neo-project/neo-modules
        ref: v3.0.1
        path: .modules
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install Libraries
      run: sudo apt-get install -y libleveldb-dev sqlite3 libsqlite3-dev libunwind8-dev
    - name: Restore Neo Node
      run: cd .node/neo-cli && dotnet restore
    - name: Restore Neo Modules
      run: cd .modules/src/LevelDBStore && dotnet restore
    - name: Build Neo Node
      run: cd .node/neo-cli && dotnet publish -c Release
    - name: Build Neo Modules
      run: cd .modules/src/LevelDBStore && dotnet publish -c Release
    - name: Install Plugins
      run: mkdir -p .node/neo-cli/bin/Release/net5.0/Plugins && cp .modules/src/LevelDBStore/bin/Release/net5.0/LevelDBStore.dll .node/neo-cli/bin/Release/net5.0/Plugins/
    - name: Run
      run: python3 run.py
    - name: Save
      run: |
        git config --global user.email "lazynode@protonmail.com"
        git config --global user.name "lazynode"
        git add .
        git commit -m release
        git push
